baseURL = "https://dab23.archaeological.science"
theme = "salinger"
title = "DAB23"
copyright = ''
ignoreErrors = ["error-remote-getjson"]

[params]
DateFormat = "2 January 2006"

author = "DAB23 Organising Committee"
description = "Colloquium held at the University of Bern, 1–3 February 2023."
header = "Digital Archaeology Bern"
keywords = [ "Portfolio", "developer", "coding", "maker"]
#googleAnalytics = ""

mainSections = ['news']

showHeaderOnHomepage = true
toc = true
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[[params.social]]
name = "email"
icon = "fa fa-envelope"
url = "mailto:dab.iaw@unibe.ch"

[[params.social]]
name = "github"
icon = "fa fa-github"
url = "https://github.com/BernCoDALab/dab23"

[Menu]
[[Menu.Main]]
name = "About"
url = "/about"
weight = 1

[[Menu.Main]]
name = "Programme"
url = "/abstracts"
weight = 3

[[Menu.Main]]
name = "Workshops"
url = "/workshops"
weight = 3.5

[[Menu.Main]]
name = "Registration"
url = "https://www.conftool.com/dab2023"
weight = 4

[[Menu.Main]]
name = "Key Dates"
url = "/calendar"
weight = 5

[[Menu.Main]]
name = "Venue"
url = "/venue"
weight = 10

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
